import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span >DailyNews</span>
        </h1>

        <p className={styles.description}>
          Keep yourself updated  with {' '}
          <code className={styles.code}>LATEST NEWS </code>
        </p>

        <div className={styles.grid}>
            <h2 className={styles.card}><Link href="/mainPage">Check out latest news &rarr;</Link></h2>
            <p>From buisness to movies ,From politics to Sport we got you covered</p>
        </div>
      </main>
    </div>
  )
}

export default Home
